### ISSUE TITLE
Class methods should return wrapped instance even if called on instances.

### ISSUE THREAD

**Issue by proofit404** [proofit404/generics#214]
```pycon
>>> import generics
>>> import dataclasses
>>> @generics.private
... @dataclasses.dataclass
... class User:
...     name: str
...     def hello(self):
...         ...
...     @classmethod
...     def new(cls):
...         return 1
...
>>> User.new()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/proofit404/t/venv/lib/python3.9/site-packages/_generics/private.py", line 119, in method
    raise GenericInstanceError(message)
_generics.exceptions.GenericInstanceError: 'new' classmethod should return an instance of the 'User' class
>>> user = User('Jeff')
>>> user.new()
1
```

**Comment by proofit404** [comment]
Superseded by #220
